### ISSUE TITLE
Impossible to use with Java 8, 11

### ISSUE THREAD

**Issue by TigranOhanyan** [ornicar/scalalib#16]
The binary is built for java 12, which makes it incompatible with java < 12. Is there a particular reason for that?

**Comment by ornicar** [comment]
The reason is that I don't need it to run on Java 11, and this lib is for personal usage. Feel free to fork it and/or build it with a different target.

**Comment by ornicar** [comment]
I understand, but Java 11 is now 5 years old and we now have another LTS: Java 17. Time to move on :rocket:
