### ISSUE TITLE
specs2 should only be used in tests

### ISSUE THREAD

**Issue by ngocdaothanh** [ornicar/scalalib#5]
In current [Build.scala](https://github.com/ornicar/scalalib/blob/master/project/Build.scala):

```
"org.specs2" %% "specs2-core" % "3.6"
```

It should be:

```
"org.specs2" %% "specs2-core" % "3.6" % "test"
```

Also, the indent of `libraryDependencies` is not correct.

--------

Size of specs2:

```
2.0M specs2-common_2.11-3.6.jar
1.9M specs2-core_2.11-3.6.jar
2.7M specs2-matcher_2.11-3.6.jar
```

**Comment by ornicar** [comment]
no, because scalalib adds specs2 tooling.
